### ISSUE TITLE
Could you export this as a calendar file?

### ISSUE THREAD

**Issue by Mateoismo** [quantum5/qcal#1]
I would like to add this to my Google Calendar. And I like your calculation which unlike others follows the original idea about leap years. Given my lack of technical capabilities I can only ask you if you could implement this export feature somehow.
Thank you very much!

**Comment by quantum5** [comment]
Implemented in b5252506d7f840678f88873ad2044a9f3a8aa956, available on https://frcal.qt.ax. Simply enter the date range you want and it'll download a calendar file.
